local L = LibStub("AceLocale-3.0"):NewLocale("ErrorMonster", "zhTW")
if not L then return end

L["Shows the current filters and their ID."] = "顯示目前過濾清單及ID"
L["Adds the given filter to the ignore list."] = "把特定過濾訊息加入至忽略列表"
L["<filter>"] = "<過濾訊息>"
L["Removes the given filter or ID from the filter list."] = "把特定過濾訊息或ID從過濾列表中移除"
L["Adding filter: "] = "加入過濾訊息："
L["Removing filter: "] = "移除過濾訊息："
L["Filter not found: "] = "過濾訊息未找到："
L["Active filters:"] = "生效的過濾訊息："
L["Throttle errors at the given rate in seconds."] = "控制一定時間（以秒計）内反覆出現的錯誤"
L["Go berserk and eat all the errors."] = "狂暴！吃掉所有錯誤訊息！"
L["Teach your ErrorMonster to aggro on other message types."] = "教會ErrorMonster吸收其他類型的訊息"
L["Error messages."] = "錯誤訊息"
L["Information messages."] = "提示訊息"
L["System messages."] = "系统訊息"
L["System messages"] = "系统訊息"
L["|cffff0000Ignore|r"] = "|cffff0000忽略|r"
L["|cff00ff00Aggro|r"] = "|cffff0000吸收|r"

L["list"] = "列表"
L["add"] = "加入"
L["remove"] = "移除"
L["throttle"] = "節流"
L["berserk"] = "狂暴"
L["aggro"] = "吸收"
L["error"] = "錯誤"
L["information"] = "提示"
L["system"] = "系統"

